name: CI

on:
  push:
    branches:
      - main  # Se déclenche quand tu pushes sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Télécharge ton code depuis GitHub

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Prépare Docker pour build

    - name: Build Docker image
      run: docker build -t myapp .  # Build l’image Docker

    - name: Run tests
      run: docker run myapp pytest  # Lance les tests (si tu en as)
